# Generated by Django 5.1.3 on 2026-07-25 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_product',
                'indexes': [models.Index(fields=['tenant_id', 'name'], name='inventory_p_tenant__6738c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(default='manual', max_length=40)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'indexes': [models.Index(fields=['tenant_id', 'product'], name='inventory_s_tenant__85f2ab_idx')],
            },
        ),
        *enable_rls("inventory_product"),
        *enable_rls("inventory_stock_movement"),
    ]
