# Generated by Django 5.1.3 on 2026-07-25 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processado')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'common_outbox_event',
                'indexes': [models.Index(fields=['status', 'occurred_at'], name='common_outb_status_0f1fb3_idx')],
            },
        ),
    ]
