# Generated by Django 5.1.3 on 2026-07-25 05:19

import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('to', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='sent', max_length=20)),
            ],
            options={
                'db_table': 'notifications_notification',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'source_event_id'), name='uniq_notification_source_event')],
            },
        ),
        *enable_rls("notifications_notification"),
    ]
