# Generated by Django 5.1.3 on 2026-07-25 12:41

import django.core.validators
import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('professional_id', models.UUIDField()),
                ('ticket_id', models.UUIDField()),
                ('base_cents', models.BigIntegerField()),
                ('percent_bps', models.PositiveIntegerField()),
                ('amount_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga')], default='pending', max_length=20)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commissions_commission',
                'indexes': [models.Index(fields=['tenant_id', 'professional_id'], name='commissions_tenant__997ae8_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'source_event_id'), name='uniq_commission_source_event')],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('professional_id', models.UUIDField(blank=True, null=True)),
                ('percent_bps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
            ],
            options={
                'db_table': 'commissions_rule',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'professional_id'), name='uniq_commission_rule_prof')],
            },
        ),
        *enable_rls("commissions_commission"),
        *enable_rls("commissions_rule"),
    ]
