# Generated by Django 5.1.3 on 2026-07-25 01:13

import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'staff_professional',
                'indexes': [models.Index(fields=['tenant_id', 'name'], name='staff_profe_tenant__ad2ec9_idx')],
            },
        ),
        # Ativa RLS + política de isolamento na tabela de negócio.
        *enable_rls("staff_professional"),
    ]
