# Generated by Django 5.1.3 on 2026-07-25 12:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('customer_id', models.UUIDField()),
                ('appointment_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada')], default='open', max_length=20)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_ticket',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='finance_tic_tenant__4c08c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('amount_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('pix', 'Pix')], default='pix', max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.ticket')),
            ],
            options={
                'db_table': 'finance_payment',
                'indexes': [models.Index(fields=['tenant_id', 'ticket'], name='finance_pay_tenant__d680bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('description', models.CharField(max_length=200)),
                ('service_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.ticket')),
            ],
            options={
                'db_table': 'finance_ticket_item',
                'indexes': [models.Index(fields=['tenant_id', 'ticket'], name='finance_tic_tenant__bf530a_idx')],
            },
        ),
        *enable_rls("finance_ticket"),
        *enable_rls("finance_payment"),
        *enable_rls("finance_ticket_item"),
    ]
