# Generated by Django 5.1.3 on 2026-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
