# Generated by Django 5.1.3 on 2026-07-25 00:50

import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tenant_company',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'db_table': 'tenant_branch',
                'indexes': [models.Index(fields=['tenant_id', 'name'], name='tenant_bran_tenant__3acef6_idx')],
            },
        ),
        # Ativa Row-Level Security + política de isolamento na tabela de negócio.
        # Ver apps/common/rls.py e docs/architecture/multi-tenant.md.
        *enable_rls("tenant_branch"),
    ]
