# Generated by Django 5.1.3 on 2026-07-25 01:06

import django.core.validators
import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_cents', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_service',
                'indexes': [models.Index(fields=['tenant_id', 'name'], name='catalog_ser_tenant__e1da94_idx')],
            },
        ),
        # Ativa RLS + política de isolamento na tabela de negócio.
        *enable_rls("catalog_service"),
    ]
