# Generated by Django 5.1.3 on 2026-07-25 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marketing_campaign',
                'indexes': [models.Index(fields=['tenant_id', 'name'], name='marketing_c_tenant__6d0a7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('customer_id', models.UUIDField()),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'marketing_loyalty_account',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'customer_id'), name='uniq_loyalty_account_customer')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(default='earn', max_length=40)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='marketing.loyaltyaccount')),
            ],
            options={
                'db_table': 'marketing_loyalty_entry',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'source_event_id'), name='uniq_loyalty_entry_source_event')],
            },
        ),
        *enable_rls("marketing_campaign"),
        *enable_rls("marketing_loyalty_account"),
        *enable_rls("marketing_loyalty_entry"),
    ]
