# Generated by Django 5.1.3 on 2026-07-25 01:21

import uuid
from django.db import migrations, models

from apps.common.rls import enable_rls

# Impede dois agendamentos ATIVOS sobrepostos para o mesmo profissional (por tenant).
# Usa btree_gist (extensão trusted) + range temporal semiaberto [starts_at, ends_at).
# É a rede de segurança da invariante já checada no use case (services.py).
NO_OVERLAP_SQL = """
    CREATE EXTENSION IF NOT EXISTS btree_gist;
    ALTER TABLE scheduling_appointment
        ADD CONSTRAINT appointment_no_overlap
        EXCLUDE USING gist (
            tenant_id WITH =,
            professional_id WITH =,
            tstzrange(starts_at, ends_at) WITH &&
        ) WHERE (status = 'booked');
"""
NO_OVERLAP_REVERSE = """
    ALTER TABLE scheduling_appointment DROP CONSTRAINT IF EXISTS appointment_no_overlap;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('professional_id', models.UUIDField()),
                ('service_id', models.UUIDField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Agendado'), ('cancelled', 'Cancelado')], default='booked', max_length=20)),
            ],
            options={
                'db_table': 'scheduling_appointment',
                'indexes': [models.Index(fields=['tenant_id', 'professional_id', 'starts_at'], name='scheduling__tenant__c3c02f_idx')],
            },
        ),
        # Isolamento por tenant (RLS) + invariante de não-sobreposição no banco.
        *enable_rls("scheduling_appointment"),
        migrations.RunSQL(sql=NO_OVERLAP_SQL, reverse_sql=NO_OVERLAP_REVERSE),
    ]
