# Generated by Django 5.1.3 on 2026-07-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gestor'), ('professional', 'Profissional'), ('reception', 'Recepção')], default='reception', max_length=20),
        ),
    ]
